sudo: true
language: java
matrix:
  include:
    - jdk: oraclejdk8
 
env:
  - JACOCO_COVERAGE=true

script:
  - "./scripts/run_travis.sh"

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_install:
- openssl aes-256-cbc -K $encrypted_0a71570cbb11_key -iv $encrypted_0a71570cbb11_iv
  -in profile.json.enc -out profile.json -d
