name: Snowpipe Java SDK Tests Against Azure Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '**'

jobs:
  build-azure:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ 8 ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Decrypt profile.json
        env:
          DECRYPTION_PASSPHRASE: ${{ secrets.PROFILE_JSON_DECRYPT_PASSPHRASE }}
        run: |
          ./scripts/decrypt_secret.sh 'AZURE'

      - name: Unit & Integration Test
        env:
          JACOCO_COVERAGE: true
          WHITESOURCE_API_KEY: ${{ secrets.WHITESOURCE_API_KEY }}
        continue-on-error: false
        run: |
          ./scripts/run_gh_actions.sh

      - name: Code Coverage
        uses: codecov/codecov-action@v1
